### PR TITLE
User interface 2

### PR DESCRIPTION
**Pull request by shadrxcc**
This contains the main.rb file which is responsible for user interaction. In this milestone, we only created content in this file. Steps needed to play the game:
what is needed from a player to 
what is needed to display for a player were put into consideration.
The display for this branch prompts for users (hint: “puts”/“print”), collect user input (hint: “get.chomp”) and only mocks the basic flow of the game. We made sure that the game can be run with the executable file and played around with the basic flow. The basic game flow implemented includes the steps present in the gif displayed in the project module.

### CODE REVIEW

**Review by soieducation — COMMENTED** [review]
Hi @YinkTech, @shadrxcc and @Ademola101, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

You have submitted a project with linters that are not passing.

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by soieducation** [comment]
To check linters locally use rubocop, and to autofix them use rubocop -a or rubocop -A

**Review by soieducation — APPROVED** [review]
Hi @shadrxcc, @Ademola101 and @YinkTech, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
6vEo


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Ademola101** [comment]
🤝🤝

**Pull request merged**
